# Planner Configuration
planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0
    planner_plugins: ["NavfnPlanner"]
    NavfnPlanner:
      plugin: "nav2_navfn_planner/NavfnPlanner"

# Controller Configuration
controller_server:
  ros__parameters:
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

# Local Costmap
local_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: waffle2/base_link
    update_frequency: 5.0
    publish_frequency: 2.0
    width: 3
    height: 3
    resolution: 0.05
    footprint: "[ [0.175, 0.16], [-0.175, 0.16], [-0.175, -0.16], [0.175, -0.16] ]"
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

# Global Costmap
global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: waffle2/base_link
    resolution: 0.05
    track_unknown_space: true
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
