amcl:
  ros__parameters:
    use_sim_time: false
    scan_topic: /waffle2/scan
    odom_frame_id: odom
    base_frame_id: base_link
    ...

map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: ""

bt_navigator:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    robot_base_frame: base_link
    ...

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 10.0

behavior_server:
  ros__parameters:
    use_sim_time: false
